# Etapa de construcción
FROM node:18 AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --production 

COPY . .

RUN yarn build 

RUN ls /app

# Etapa de producción
FROM nginx:alpine

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

# Puerto de escucha
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
